language: node_js
node_js: 
  - "8"
  - "10"

env:
  - PGUSER=postgres PGDATABASE=postgres

services:
  - postgresql

cache:
  directories:
    - "node_modules"

after_success: npx nyc report --reporter=lcov > coverage.lcov && npx codecov
